export const TOURNAMENT_LIMITS = {
	MIN_TEAMS: 4,
	MAX_TEAMS: 64,
	MIN_COURTS: 1,
	MAX_COURTS: 20,
	MAX_TOURNAMENT_DAYS: 7,
	MIN_REGISTRATION_DAYS: 1,
};

export const TEAM_REQUIREMENTS = {
	PLAYERS_PER_TEAM: 2,
	MIN_AGE: 12,
	MAX_NAME_LENGTH: 50,
};
