// Mock tournament data for testing
import { Tournament } from '@/types/types';

export const mockTournaments: Tournament[] = [
	// Active tournament - tennis singles, partially completed
	{
		id: 'tournament-1',
		name: 'Sommarturnering Tennis 2025',
		format: 'round-robin', // Assuming this matches your TOURNAMENT_FORMATS
		matchFormat: 'best-of-3', // Assuming this matches your MATCH_FORMATS
		scoringSystem: 'sets', // Assuming this matches your SCORING
		courtCount: 2,
		courtNames: ['Bana 1', 'Bana 2'],
		participants: [
			'Anna Andersson',
			'Björn Borg',
			'Cecilia Carlsson',
			'David Danielsson',
		],
		startDate: '2025-06-15',
		createdAt: '2025-06-10T09:00:00.000Z',
		status: 'active',
		rounds: [
			[
				{
					id: 'match-1-1',
					participantA: 'Anna Andersson',
					participantB: 'Björn Borg',
					court: 'Bana 1',
					scoreA: 2,
					scoreB: 1,
					status: 'completed',
				},
				{
					id: 'match-1-2',
					participantA: 'Cecilia Carlsson',
					participantB: 'David Danielsson',
					court: 'Bana 2',
					scoreA: 2,
					scoreB: 0,
					status: 'completed',
				},
			],
			[
				{
					id: 'match-2-1',
					participantA: 'Anna Andersson',
					participantB: 'Cecilia Carlsson',
					court: 'Bana 1',
					scoreA: 1,
					scoreB: 2,
					status: 'completed',
				},
				{
					id: 'match-2-2',
					participantA: 'Björn Borg',
					participantB: 'David Danielsson',
					court: 'Bana 2',
					scoreA: null,
					scoreB: null,
					status: 'pending',
				},
			],
			[
				{
					id: 'match-3-1',
					participantA: 'Anna Andersson',
					participantB: 'David Danielsson',
					court: 'Bana 1',
					scoreA: null,
					scoreB: null,
					status: 'pending',
				},
				{
					id: 'match-3-2',
					participantA: 'Björn Borg',
					participantB: 'Cecilia Carlsson',
					court: 'Bana 2',
					scoreA: null,
					scoreB: null,
					status: 'pending',
				},
			],
		],
	},

	// Completed tournament - badminton doubles teams
	{
		id: 'tournament-2',
		name: 'Företagsturnering Badminton',
		format: 'round-robin',
		matchFormat: 'best-of-3',
		scoringSystem: 'points',
		courtCount: 3,
		courtNames: ['Hall A', 'Hall B', 'Hall C'],
		participants: [
			'Team Alpha',
			'Team Beta',
			'Team Gamma',
			'Team Delta',
			'Team Echo',
		],
		startDate: '2025-05-20',
		createdAt: '2025-05-15T14:30:00.000Z',
		status: 'completed',
		winner: 'Team Gamma',
		rounds: [
			[
				{
					id: 'match-2-1-1',
					participantA: 'Team Alpha',
					participantB: 'Team Beta',
					court: 'Hall A',
					scoreA: 21,
					scoreB: 18,
					status: 'completed',
				},
				{
					id: 'match-2-1-2',
					participantA: 'Team Gamma',
					participantB: 'Team Delta',
					court: 'Hall B',
					scoreA: 21,
					scoreB: 15,
					status: 'completed',
				},
			],
			[
				{
					id: 'match-2-2-1',
					participantA: 'Team Echo',
					participantB: 'Team Alpha',
					court: 'Hall A',
					scoreA: 19,
					scoreB: 21,
					status: 'completed',
				},
				{
					id: 'match-2-2-2',
					participantA: 'Team Beta',
					participantB: 'Team Gamma',
					court: 'Hall B',
					scoreA: 16,
					scoreB: 21,
					status: 'completed',
				},
			],
			[
				{
					id: 'match-2-3-1',
					participantA: 'Team Delta',
					participantB: 'Team Echo',
					court: 'Hall A',
					scoreA: 21,
					scoreB: 17,
					status: 'completed',
				},
				{
					id: 'match-2-3-2',
					participantA: 'Team Alpha',
					participantB: 'Team Gamma',
					court: 'Hall B',
					scoreA: 18,
					scoreB: 21,
					status: 'completed',
				},
			],
			[
				{
					id: 'match-2-4-1',
					participantA: 'Team Beta',
					participantB: 'Team Delta',
					court: 'Hall A',
					scoreA: 20,
					scoreB: 22,
					status: 'completed',
				},
				{
					id: 'match-2-4-2',
					participantA: 'Team Echo',
					participantB: 'Team Gamma',
					court: 'Hall B',
					scoreA: 15,
					scoreB: 21,
					status: 'completed',
				},
			],
			[
				{
					id: 'match-2-5-1',
					participantA: 'Team Alpha',
					participantB: 'Team Delta',
					court: 'Hall A',
					scoreA: 21,
					scoreB: 19,
					status: 'completed',
				},
				{
					id: 'match-2-5-2',
					participantA: 'Team Beta',
					participantB: 'Team Echo',
					court: 'Hall B',
					scoreA: 18,
					scoreB: 21,
					status: 'completed',
				},
			],
		],
	},

	// Active tournament - table tennis, just started
	{
		id: 'tournament-3',
		name: 'Pingis Liga Vinter',
		format: 'round-robin',
		matchFormat: 'best-of-5',
		scoringSystem: 'sets',
		courtCount: 1,
		courtNames: ['Bord 1'],
		participants: ['Erik Eriksson', 'Frida Fredriksson', 'Gustav Gustafsson'],
		startDate: '2025-06-19',
		createdAt: '2025-06-18T16:45:00.000Z',
		status: 'active',
		rounds: [
			[
				{
					id: 'match-3-1-1',
					participantA: 'Erik Eriksson',
					participantB: 'Frida Fredriksson',
					court: 'Bord 1',
					scoreA: 3,
					scoreB: 1,
					status: 'completed',
				},
			],
			[
				{
					id: 'match-3-2-1',
					participantA: 'Gustav Gustafsson',
					participantB: 'Erik Eriksson',
					court: 'Bord 1',
					scoreA: null,
					scoreB: null,
					status: 'pending',
				},
			],
			[
				{
					id: 'match-3-3-1',
					participantA: 'Frida Fredriksson',
					participantB: 'Gustav Gustafsson',
					court: 'Bord 1',
					scoreA: null,
					scoreB: null,
					status: 'pending',
				},
			],
		],
	},

	// Completed tournament - volleyball teams
	{
		id: 'tournament-4',
		name: 'Beachvolley Masters',
		format: 'round-robin',
		matchFormat: 'best-of-3',
		scoringSystem: 'sets',
		courtCount: 2,
		courtNames: ['Sand Court 1', 'Sand Court 2'],
		participants: ['Spike & Dig', 'Net Ninjas', 'Sand Storms', 'Beach Bombers'],
		startDate: '2025-05-01',
		createdAt: '2025-04-25T11:20:00.000Z',
		status: 'completed',
		winner: 'Net Ninjas',
		rounds: [
			[
				{
					id: 'match-4-1-1',
					participantA: 'Spike & Dig',
					participantB: 'Net Ninjas',
					court: 'Sand Court 1',
					scoreA: 1,
					scoreB: 2,
					status: 'completed',
				},
				{
					id: 'match-4-1-2',
					participantA: 'Sand Storms',
					participantB: 'Beach Bombers',
					court: 'Sand Court 2',
					scoreA: 2,
					scoreB: 0,
					status: 'completed',
				},
			],
			[
				{
					id: 'match-4-2-1',
					participantA: 'Spike & Dig',
					participantB: 'Sand Storms',
					court: 'Sand Court 1',
					scoreA: 0,
					scoreB: 2,
					status: 'completed',
				},
				{
					id: 'match-4-2-2',
					participantA: 'Net Ninjas',
					participantB: 'Beach Bombers',
					court: 'Sand Court 2',
					scoreA: 2,
					scoreB: 1,
					status: 'completed',
				},
			],
			[
				{
					id: 'match-4-3-1',
					participantA: 'Spike & Dig',
					participantB: 'Beach Bombers',
					court: 'Sand Court 1',
					scoreA: 2,
					scoreB: 1,
					status: 'completed',
				},
				{
					id: 'match-4-3-2',
					participantA: 'Net Ninjas',
					participantB: 'Sand Storms',
					court: 'Sand Court 2',
					scoreA: 2,
					scoreB: 0,
					status: 'completed',
				},
			],
		],
	},

	// Active tournament - squash, large field
	{
		id: 'tournament-5',
		name: 'Squash Open Championship',
		format: 'round-robin',
		matchFormat: 'best-of-5',
		scoringSystem: 'games',
		courtCount: 3,
		courtNames: ['Court A', 'Court B', 'Court C'],
		participants: [
			'Helena Holm',
			'Ivan Ivanov',
			'Jenny Jansson',
			'Karl Karlsson',
			'Linda Larsson',
			'Magnus Magnusson',
		],
		startDate: '2025-06-22',
		createdAt: '2025-06-19T08:15:00.000Z',
		status: 'active',
		rounds: [
			[
				{
					id: 'match-5-1-1',
					participantA: 'Helena Holm',
					participantB: 'Ivan Ivanov',
					court: 'Court A',
					scoreA: 3,
					scoreB: 2,
					status: 'completed',
				},
				{
					id: 'match-5-1-2',
					participantA: 'Jenny Jansson',
					participantB: 'Karl Karlsson',
					court: 'Court B',
					scoreA: 3,
					scoreB: 0,
					status: 'completed',
				},
				{
					id: 'match-5-1-3',
					participantA: 'Linda Larsson',
					participantB: 'Magnus Magnusson',
					court: 'Court C',
					scoreA: 1,
					scoreB: 3,
					status: 'completed',
				},
			],
			[
				{
					id: 'match-5-2-1',
					participantA: 'Helena Holm',
					participantB: 'Jenny Jansson',
					court: 'Court A',
					scoreA: 2,
					scoreB: 3,
					status: 'completed',
				},
				{
					id: 'match-5-2-2',
					participantA: 'Ivan Ivanov',
					participantB: 'Linda Larsson',
					court: 'Court B',
					scoreA: 3,
					scoreB: 1,
					status: 'completed',
				},
				{
					id: 'match-5-2-3',
					participantA: 'Karl Karlsson',
					participantB: 'Magnus Magnusson',
					court: 'Court C',
					scoreA: null,
					scoreB: null,
					status: 'pending',
				},
			],
			// More rounds would follow...
		],
	},
];

// You can use this in your store's initial state like:
// activeTournaments: mockTournaments.filter(t => t.status === 'active'),
// completedTournaments: mockTournaments.filter(t => t.status === 'completed'),
