import { TOURNAMENT_FORMATS } from '@/constants';

export const ACTIVE_TOURNAMENT_FORMATS_CONFIG = {
	AMERICANO_SINGLES: TOURNAMENT_FORMATS.AMERICANO_SINGLES,
	AMERICANO_DOUBLES: TOURNAMENT_FORMATS.AMERICANO_DOUBLES,
	MEXICANO_SINGLES: TOURNAMENT_FORMATS.MEXICANO_SINGLES,
	MEXICANO_DOUBLES: TOURNAMENT_FORMATS.MEXICANO_DOUBLES,
	BEAT_THE_BOX: TOURNAMENT_FORMATS.BEAT_THE_BOX,
};
